---
abstract: 'export lexical variables'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exporter-LexicalVars
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Exporter::LexicalVars:
    file: lib/Exporter/LexicalVars.pm
    version: 0.000_01
requires:
  B::Hooks::Parser: 0
  Exporter::Shiny: 0
  perl: 5.008003
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Exporter-LexicalVars/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Exporter-LexicalVars
  homepage: https://metacpan.org/release/Exporter-LexicalVars
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-exporter-lexicalvars.git
version: 0.000_01
